# Criando pedido / Adicionando item a um pedido aberto
POST http://localhost:8000/orders/vanessa@gmail.com

{
    "product_id": "633f6144da7ebbccd1b22bbe",
    "product_quantity": 1
}

###

# Buscando por pedido aberto do usuário
GET http://localhost:8000/orders/vanessa@gmail.com/order/?order_status=opened

###

# Buscando por pedidos fechados do usuário

GET http://localhost:8000/orders/vanessa@gmail.com/order/?order_status=closed

###

# Passando o parâmetro opcional orders_quantity que retorna apenas a quantidade
# de pedidos encontrados para o usuário

GET http://localhost:8000/orders/vanessa@gmail.com/order/?order_status=closed&orders_quantity=true

###

# Removendo um item do pedido aberto

DELETE http://localhost:8000/orders/vanessa@gmail.com

{
    "product_id": "633f6144da7ebbccd1b22bbe",
    "product_quantity": 1
}
