#Cadastro do usuário
POST http://localhost:8000/users/

{
    "email": "ada.teste@gmail.com",
    "password": "234oi67",
    "is_active": true,
    "is_admin": false
}

###
#Cadastro com senha muito curta
POST http://localhost:8000/users/

{
    "email": "ada.teste@gmail.com",
    "password": "27",
    "is_active": true,
    "is_admin": false
}

#Busca com email valido
###
GET http://localhost:8000/users/ada.teste@gmail.com

#Busca com email inexistente
###
GET http://localhost:8000/users/aka.teste@gmail.com

#Apagar usuário
###
DELETE http://localhost:8000/users/63476dafca49a6eb9e9ba6ab