# Criando um endereço

POST http://localhost:8000/user/vanessa@gmail.com/address/

{
    "street" : "Rua Quarenta e Sete, Numero 3",
    "cep" : "15312000",
    "district" : "São Paulo",
    "city" : "São Paulo",
    "state" : "São Paulo",
    "is_delivery" : true
}

### 

# Buscando todos os endereços do usuário

GET http://localhost:8000/user/vanessa@gmail.com/address/

###

# Deletando endereço pelo id

DELETE http://localhost:8000/user/vanessa@gmail.com/address/6341e735dcc553df4ebafcc7

###

# Busca um endereço do usuário pelo id

GET http://localhost:8000/user/vanessa@gmail.com/address/6341e735dcc553df4ebafcc7
