# Criando um endereço

POST http://localhost:8000/user/vanessa@gmail.com/address/

{
    "street" : "Rua Quarenta e Sete, Numero 3",
    "cep" : "12345000",
    "district" : "São Paulo",
    "city" : "São Paulo",
    "state" : "São Paulo",
    "is_delivery" : false
}

### 

# Buscando todos os endereços do usuário

GET http://localhost:8000/user/vanessa@gmail.com/address/

###

# Deletando endereço pelo id

DELETE http://localhost:8000/user/vanessa@gmail.com/address/6347724474aa1592e7aaacbc

###

# Busca um endereço do usuário pelo id

GET http://localhost:8000/user/vanessa@gmail.com/address/6347725674aa1592e7aaacbe
